services:
  f1:
    build: .
    environment:
      APP_ID: $APP_ID
      API_HASH: $API_HASH
      SUDO_USERS: $SUDO_USERS
      BOT_TOKEN: $BOT_TOKEN
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
    command: python3 encoder.py
